on: [push]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1

            - name: Setup SSH Keys and known_hosts
              env:
                 SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                    ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                    ssh-add - <<< "${{ secrets.HELLO_WORLD_JS_ACTION_READONLY_ACCESS_PRIVATE_KEY }}"

            - name: Some task that fetches dependencies
              env:
                SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                run: ./fetch-dependencies.sh
            - name: hello world action step
              id: hello
              #uses: ./.github/actions/hello-world-javascript-action
              #uses: https://github.com/crinabucur/hello-world-javascript-action
              uses: crinabucur/hello-world-javascript-action@v1.1
              with:
                  who-to-greet: 'crina catalina bucur'
              # use the output from the `hello` step
            - name: get the output time
              run: echo "the time was ${{ steps.hello.outputs.time }}"