on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@v2
        - name: Setup SSH Keys and known_hosts
             env:
               SSH_AUTH_SOCK: /tmp/ssh_agent.sock
             run: |
               ssh-agent -a $SSH_AUTH_SOCK > /dev/null
               ssh-add - <<< "${{ secrets.HELLO_WORLD_JS_ACTION_READONLY_ACCESS_PRIVATE_KEY }}"

        - name: Some task that fetches dependencies
             env:
               SSH_AUTH_SOCK: /tmp/ssh_agent.sock
             run: ./fetch-deps.sh
      - name: Hello world action step
        id: hello
        uses: https://github.com/crinabucur/hello-world-javascript-action
        with:
          who-to-greet: 'Crina Catalina Bucur'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"